// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeWrite.proto

package com.example.wewritebeta;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TextCarrierOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string text = 1;
    /**
     * <code>repeated string text = 1;</code>
     */
    java.util.List<java.lang.String>
    getTextList();
    /**
     * <code>repeated string text = 1;</code>
     */
    int getTextCount();
    /**
     * <code>repeated string text = 1;</code>
     */
    java.lang.String getText(int index);
    /**
     * <code>repeated string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes(int index);

    // optional int32 cursorLoc = 2;
    /**
     * <code>optional int32 cursorLoc = 2;</code>
     */
    boolean hasCursorLoc();
    /**
     * <code>optional int32 cursorLoc = 2;</code>
     */
    int getCursorLoc();

    // optional string changedBy = 3;
    /**
     * <code>optional string changedBy = 3;</code>
     */
    boolean hasChangedBy();
    /**
     * <code>optional string changedBy = 3;</code>
     */
    java.lang.String getChangedBy();
    /**
     * <code>optional string changedBy = 3;</code>
     */
    com.google.protobuf.ByteString
        getChangedByBytes();
  }
  /**
   * Protobuf type {@code WeWriteBeta.TextCarrier}
   */
  public static final class TextCarrier extends
      com.google.protobuf.GeneratedMessage
      implements TextCarrierOrBuilder {
    // Use TextCarrier.newBuilder() to construct.
    private TextCarrier(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TextCarrier(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TextCarrier defaultInstance;
    public static TextCarrier getDefaultInstance() {
      return defaultInstance;
    }

    public TextCarrier getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TextCarrier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                text_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              text_.add(input.readBytes());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              cursorLoc_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              changedBy_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = new com.google.protobuf.UnmodifiableLazyStringList(text_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.wewritebeta.MessageProtos.internal_static_WeWriteBeta_TextCarrier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.wewritebeta.MessageProtos.internal_static_WeWriteBeta_TextCarrier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.wewritebeta.MessageProtos.TextCarrier.class, com.example.wewritebeta.MessageProtos.TextCarrier.Builder.class);
    }

    public static com.google.protobuf.Parser<TextCarrier> PARSER =
        new com.google.protobuf.AbstractParser<TextCarrier>() {
      public TextCarrier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextCarrier(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TextCarrier> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // repeated string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList text_;
    /**
     * <code>repeated string text = 1;</code>
     */
    public java.util.List<java.lang.String>
        getTextList() {
      return text_;
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public int getTextCount() {
      return text_.size();
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public java.lang.String getText(int index) {
      return text_.get(index);
    }
    /**
     * <code>repeated string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes(int index) {
      return text_.getByteString(index);
    }

    // optional int32 cursorLoc = 2;
    public static final int CURSORLOC_FIELD_NUMBER = 2;
    private int cursorLoc_;
    /**
     * <code>optional int32 cursorLoc = 2;</code>
     */
    public boolean hasCursorLoc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 cursorLoc = 2;</code>
     */
    public int getCursorLoc() {
      return cursorLoc_;
    }

    // optional string changedBy = 3;
    public static final int CHANGEDBY_FIELD_NUMBER = 3;
    private java.lang.Object changedBy_;
    /**
     * <code>optional string changedBy = 3;</code>
     */
    public boolean hasChangedBy() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string changedBy = 3;</code>
     */
    public java.lang.String getChangedBy() {
      java.lang.Object ref = changedBy_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          changedBy_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string changedBy = 3;</code>
     */
    public com.google.protobuf.ByteString
        getChangedByBytes() {
      java.lang.Object ref = changedBy_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        changedBy_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      cursorLoc_ = 0;
      changedBy_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < text_.size(); i++) {
        output.writeBytes(1, text_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, cursorLoc_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getChangedByBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < text_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(text_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getTextList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cursorLoc_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getChangedByBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.example.wewritebeta.MessageProtos.TextCarrier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.wewritebeta.MessageProtos.TextCarrier prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeWriteBeta.TextCarrier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.wewritebeta.MessageProtos.TextCarrierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.wewritebeta.MessageProtos.internal_static_WeWriteBeta_TextCarrier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.wewritebeta.MessageProtos.internal_static_WeWriteBeta_TextCarrier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.wewritebeta.MessageProtos.TextCarrier.class, com.example.wewritebeta.MessageProtos.TextCarrier.Builder.class);
      }

      // Construct using com.example.wewritebeta.MessageProtos.TextCarrier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        cursorLoc_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        changedBy_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.wewritebeta.MessageProtos.internal_static_WeWriteBeta_TextCarrier_descriptor;
      }

      public com.example.wewritebeta.MessageProtos.TextCarrier getDefaultInstanceForType() {
        return com.example.wewritebeta.MessageProtos.TextCarrier.getDefaultInstance();
      }

      public com.example.wewritebeta.MessageProtos.TextCarrier build() {
        com.example.wewritebeta.MessageProtos.TextCarrier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.wewritebeta.MessageProtos.TextCarrier buildPartial() {
        com.example.wewritebeta.MessageProtos.TextCarrier result = new com.example.wewritebeta.MessageProtos.TextCarrier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = new com.google.protobuf.UnmodifiableLazyStringList(
              text_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cursorLoc_ = cursorLoc_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.changedBy_ = changedBy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.wewritebeta.MessageProtos.TextCarrier) {
          return mergeFrom((com.example.wewritebeta.MessageProtos.TextCarrier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.wewritebeta.MessageProtos.TextCarrier other) {
        if (other == com.example.wewritebeta.MessageProtos.TextCarrier.getDefaultInstance()) return this;
        if (!other.text_.isEmpty()) {
          if (text_.isEmpty()) {
            text_ = other.text_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTextIsMutable();
            text_.addAll(other.text_);
          }
          onChanged();
        }
        if (other.hasCursorLoc()) {
          setCursorLoc(other.getCursorLoc());
        }
        if (other.hasChangedBy()) {
          bitField0_ |= 0x00000004;
          changedBy_ = other.changedBy_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.wewritebeta.MessageProtos.TextCarrier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.wewritebeta.MessageProtos.TextCarrier) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string text = 1;
      private com.google.protobuf.LazyStringList text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTextIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          text_ = new com.google.protobuf.LazyStringArrayList(text_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public java.util.List<java.lang.String>
          getTextList() {
        return java.util.Collections.unmodifiableList(text_);
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public int getTextCount() {
        return text_.size();
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public java.lang.String getText(int index) {
        return text_.get(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes(int index) {
        return text_.getByteString(index);
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder setText(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addAllText(
          java.lang.Iterable<java.lang.String> values) {
        ensureTextIsMutable();
        super.addAll(values, text_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder clearText() {
        text_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string text = 1;</code>
       */
      public Builder addTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTextIsMutable();
        text_.add(value);
        onChanged();
        return this;
      }

      // optional int32 cursorLoc = 2;
      private int cursorLoc_ ;
      /**
       * <code>optional int32 cursorLoc = 2;</code>
       */
      public boolean hasCursorLoc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cursorLoc = 2;</code>
       */
      public int getCursorLoc() {
        return cursorLoc_;
      }
      /**
       * <code>optional int32 cursorLoc = 2;</code>
       */
      public Builder setCursorLoc(int value) {
        bitField0_ |= 0x00000002;
        cursorLoc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLoc = 2;</code>
       */
      public Builder clearCursorLoc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cursorLoc_ = 0;
        onChanged();
        return this;
      }

      // optional string changedBy = 3;
      private java.lang.Object changedBy_ = "";
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public boolean hasChangedBy() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public java.lang.String getChangedBy() {
        java.lang.Object ref = changedBy_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          changedBy_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public com.google.protobuf.ByteString
          getChangedByBytes() {
        java.lang.Object ref = changedBy_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          changedBy_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public Builder setChangedBy(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        changedBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public Builder clearChangedBy() {
        bitField0_ = (bitField0_ & ~0x00000004);
        changedBy_ = getDefaultInstance().getChangedBy();
        onChanged();
        return this;
      }
      /**
       * <code>optional string changedBy = 3;</code>
       */
      public Builder setChangedByBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        changedBy_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WeWriteBeta.TextCarrier)
    }

    static {
      defaultInstance = new TextCarrier(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:WeWriteBeta.TextCarrier)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_WeWriteBeta_TextCarrier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_WeWriteBeta_TextCarrier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWeWrite.proto\022\013WeWriteBeta\"A\n\013TextCarr" +
      "ier\022\014\n\004text\030\001 \003(\t\022\021\n\tcursorLoc\030\002 \001(\005\022\021\n\t" +
      "changedBy\030\003 \001(\tB(\n\027com.example.wewritebe" +
      "taB\rMessageProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_WeWriteBeta_TextCarrier_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_WeWriteBeta_TextCarrier_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_WeWriteBeta_TextCarrier_descriptor,
              new java.lang.String[] { "Text", "CursorLoc", "ChangedBy", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
