// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeWrite.proto

package com.example.wewritebeta;

public final class MessageProtos {
  private MessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventCarrierOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string text = 1;
    /**
     * <code>optional string text = 1;</code>
     */
    boolean hasText();
    /**
     * <code>optional string text = 1;</code>
     */
    java.lang.String getText();
    /**
     * <code>optional string text = 1;</code>
     */
    com.google.protobuf.ByteString
        getTextBytes();

    // optional int32 startIndex = 2;
    /**
     * <code>optional int32 startIndex = 2;</code>
     */
    boolean hasStartIndex();
    /**
     * <code>optional int32 startIndex = 2;</code>
     */
    int getStartIndex();

    // optional int32 endIndex = 3;
    /**
     * <code>optional int32 endIndex = 3;</code>
     */
    boolean hasEndIndex();
    /**
     * <code>optional int32 endIndex = 3;</code>
     */
    int getEndIndex();

    // optional int32 cursorLoc = 4;
    /**
     * <code>optional int32 cursorLoc = 4;</code>
     */
    boolean hasCursorLoc();
    /**
     * <code>optional int32 cursorLoc = 4;</code>
     */
    int getCursorLoc();

    // optional int64 globalID = 5;
    /**
     * <code>optional int64 globalID = 5;</code>
     */
    boolean hasGlobalID();
    /**
     * <code>optional int64 globalID = 5;</code>
     */
    long getGlobalID();

    // optional .EventCarrier.EventType type = 6;
    /**
     * <code>optional .EventCarrier.EventType type = 6;</code>
     */
    boolean hasType();
    /**
     * <code>optional .EventCarrier.EventType type = 6;</code>
     */
    MessageProtos.EventCarrier.EventType getType();
  }
  /**
   * Protobuf type {@code EventCarrier}
   */
  public static final class EventCarrier extends
      com.google.protobuf.GeneratedMessage
      implements EventCarrierOrBuilder {
    // Use EventCarrier.newBuilder() to construct.
    private EventCarrier(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private EventCarrier(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final EventCarrier defaultInstance;
    public static EventCarrier getDefaultInstance() {
      return defaultInstance;
    }

    public EventCarrier getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private EventCarrier(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              text_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              startIndex_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              endIndex_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              cursorLoc_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              globalID_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              MessageProtos.EventCarrier.EventType value = MessageProtos.EventCarrier.EventType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                bitField0_ |= 0x00000020;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProtos.internal_static_EventCarrier_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProtos.internal_static_EventCarrier_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageProtos.EventCarrier.class, MessageProtos.EventCarrier.Builder.class);
    }

    public static com.google.protobuf.Parser<EventCarrier> PARSER =
        new com.google.protobuf.AbstractParser<EventCarrier>() {
      public EventCarrier parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventCarrier(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<EventCarrier> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code EventCarrier.EventType}
     */
    public enum EventType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INSERT = 0;</code>
       */
      INSERT(0, 0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1, 1),
      /**
       * <code>CURSOR = 2;</code>
       */
      CURSOR(2, 2),
      /**
       * <code>UNDO = 3;</code>
       */
      UNDO(3, 3),
      /**
       * <code>REDO = 4;</code>
       */
      REDO(4, 4),
      ;

      /**
       * <code>INSERT = 0;</code>
       */
      public static final int INSERT_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;
      /**
       * <code>CURSOR = 2;</code>
       */
      public static final int CURSOR_VALUE = 2;
      /**
       * <code>UNDO = 3;</code>
       */
      public static final int UNDO_VALUE = 3;
      /**
       * <code>REDO = 4;</code>
       */
      public static final int REDO_VALUE = 4;


      public final int getNumber() { return value; }

      public static EventType valueOf(int value) {
        switch (value) {
          case 0: return INSERT;
          case 1: return DELETE;
          case 2: return CURSOR;
          case 3: return UNDO;
          case 4: return REDO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<EventType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
              public EventType findValueByNumber(int number) {
                return EventType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageProtos.EventCarrier.getDescriptor().getEnumTypes().get(0);
      }

      private static final EventType[] VALUES = values();

      public static EventType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private EventType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:EventCarrier.EventType)
    }

    private int bitField0_;
    // optional string text = 1;
    public static final int TEXT_FIELD_NUMBER = 1;
    private java.lang.Object text_;
    /**
     * <code>optional string text = 1;</code>
     */
    public boolean hasText() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          text_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string text = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 startIndex = 2;
    public static final int STARTINDEX_FIELD_NUMBER = 2;
    private int startIndex_;
    /**
     * <code>optional int32 startIndex = 2;</code>
     */
    public boolean hasStartIndex() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 startIndex = 2;</code>
     */
    public int getStartIndex() {
      return startIndex_;
    }

    // optional int32 endIndex = 3;
    public static final int ENDINDEX_FIELD_NUMBER = 3;
    private int endIndex_;
    /**
     * <code>optional int32 endIndex = 3;</code>
     */
    public boolean hasEndIndex() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 endIndex = 3;</code>
     */
    public int getEndIndex() {
      return endIndex_;
    }

    // optional int32 cursorLoc = 4;
    public static final int CURSORLOC_FIELD_NUMBER = 4;
    private int cursorLoc_;
    /**
     * <code>optional int32 cursorLoc = 4;</code>
     */
    public boolean hasCursorLoc() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 cursorLoc = 4;</code>
     */
    public int getCursorLoc() {
      return cursorLoc_;
    }

    // optional int64 globalID = 5;
    public static final int GLOBALID_FIELD_NUMBER = 5;
    private long globalID_;
    /**
     * <code>optional int64 globalID = 5;</code>
     */
    public boolean hasGlobalID() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int64 globalID = 5;</code>
     */
    public long getGlobalID() {
      return globalID_;
    }

    // optional .EventCarrier.EventType type = 6;
    public static final int TYPE_FIELD_NUMBER = 6;
    private MessageProtos.EventCarrier.EventType type_;
    /**
     * <code>optional .EventCarrier.EventType type = 6;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .EventCarrier.EventType type = 6;</code>
     */
    public MessageProtos.EventCarrier.EventType getType() {
      return type_;
    }

    private void initFields() {
      text_ = "";
      startIndex_ = 0;
      endIndex_ = 0;
      cursorLoc_ = 0;
      globalID_ = 0L;
      type_ = MessageProtos.EventCarrier.EventType.INSERT;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, startIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, endIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, cursorLoc_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, globalID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeEnum(6, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTextBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, startIndex_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, endIndex_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, cursorLoc_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, globalID_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static MessageProtos.EventCarrier parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProtos.EventCarrier parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProtos.EventCarrier parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageProtos.EventCarrier parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageProtos.EventCarrier parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProtos.EventCarrier parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static MessageProtos.EventCarrier parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static MessageProtos.EventCarrier parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static MessageProtos.EventCarrier parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static MessageProtos.EventCarrier parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(MessageProtos.EventCarrier prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EventCarrier}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessageProtos.EventCarrierOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProtos.internal_static_EventCarrier_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProtos.internal_static_EventCarrier_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageProtos.EventCarrier.class, MessageProtos.EventCarrier.Builder.class);
      }

      // Construct using MessageProtos.EventCarrier.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        text_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        startIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        endIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        cursorLoc_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        globalID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        type_ = MessageProtos.EventCarrier.EventType.INSERT;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProtos.internal_static_EventCarrier_descriptor;
      }

      public MessageProtos.EventCarrier getDefaultInstanceForType() {
        return MessageProtos.EventCarrier.getDefaultInstance();
      }

      public MessageProtos.EventCarrier build() {
        MessageProtos.EventCarrier result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public MessageProtos.EventCarrier buildPartial() {
        MessageProtos.EventCarrier result = new MessageProtos.EventCarrier(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.text_ = text_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.startIndex_ = startIndex_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.endIndex_ = endIndex_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cursorLoc_ = cursorLoc_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.globalID_ = globalID_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageProtos.EventCarrier) {
          return mergeFrom((MessageProtos.EventCarrier)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageProtos.EventCarrier other) {
        if (other == MessageProtos.EventCarrier.getDefaultInstance()) return this;
        if (other.hasText()) {
          bitField0_ |= 0x00000001;
          text_ = other.text_;
          onChanged();
        }
        if (other.hasStartIndex()) {
          setStartIndex(other.getStartIndex());
        }
        if (other.hasEndIndex()) {
          setEndIndex(other.getEndIndex());
        }
        if (other.hasCursorLoc()) {
          setCursorLoc(other.getCursorLoc());
        }
        if (other.hasGlobalID()) {
          setGlobalID(other.getGlobalID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageProtos.EventCarrier parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageProtos.EventCarrier) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string text = 1;
      private java.lang.Object text_ = "";
      /**
       * <code>optional string text = 1;</code>
       */
      public boolean hasText() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public java.lang.String getText() {
        java.lang.Object ref = text_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          text_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTextBytes() {
        java.lang.Object ref = text_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          text_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder clearText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        text_ = getDefaultInstance().getText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string text = 1;</code>
       */
      public Builder setTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        text_ = value;
        onChanged();
        return this;
      }

      // optional int32 startIndex = 2;
      private int startIndex_ ;
      /**
       * <code>optional int32 startIndex = 2;</code>
       */
      public boolean hasStartIndex() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 startIndex = 2;</code>
       */
      public int getStartIndex() {
        return startIndex_;
      }
      /**
       * <code>optional int32 startIndex = 2;</code>
       */
      public Builder setStartIndex(int value) {
        bitField0_ |= 0x00000002;
        startIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 startIndex = 2;</code>
       */
      public Builder clearStartIndex() {
        bitField0_ = (bitField0_ & ~0x00000002);
        startIndex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 endIndex = 3;
      private int endIndex_ ;
      /**
       * <code>optional int32 endIndex = 3;</code>
       */
      public boolean hasEndIndex() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 endIndex = 3;</code>
       */
      public int getEndIndex() {
        return endIndex_;
      }
      /**
       * <code>optional int32 endIndex = 3;</code>
       */
      public Builder setEndIndex(int value) {
        bitField0_ |= 0x00000004;
        endIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 endIndex = 3;</code>
       */
      public Builder clearEndIndex() {
        bitField0_ = (bitField0_ & ~0x00000004);
        endIndex_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cursorLoc = 4;
      private int cursorLoc_ ;
      /**
       * <code>optional int32 cursorLoc = 4;</code>
       */
      public boolean hasCursorLoc() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 cursorLoc = 4;</code>
       */
      public int getCursorLoc() {
        return cursorLoc_;
      }
      /**
       * <code>optional int32 cursorLoc = 4;</code>
       */
      public Builder setCursorLoc(int value) {
        bitField0_ |= 0x00000008;
        cursorLoc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorLoc = 4;</code>
       */
      public Builder clearCursorLoc() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cursorLoc_ = 0;
        onChanged();
        return this;
      }

      // optional int64 globalID = 5;
      private long globalID_ ;
      /**
       * <code>optional int64 globalID = 5;</code>
       */
      public boolean hasGlobalID() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int64 globalID = 5;</code>
       */
      public long getGlobalID() {
        return globalID_;
      }
      /**
       * <code>optional int64 globalID = 5;</code>
       */
      public Builder setGlobalID(long value) {
        bitField0_ |= 0x00000010;
        globalID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 globalID = 5;</code>
       */
      public Builder clearGlobalID() {
        bitField0_ = (bitField0_ & ~0x00000010);
        globalID_ = 0L;
        onChanged();
        return this;
      }

      // optional .EventCarrier.EventType type = 6;
      private MessageProtos.EventCarrier.EventType type_ = MessageProtos.EventCarrier.EventType.INSERT;
      /**
       * <code>optional .EventCarrier.EventType type = 6;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional .EventCarrier.EventType type = 6;</code>
       */
      public MessageProtos.EventCarrier.EventType getType() {
        return type_;
      }
      /**
       * <code>optional .EventCarrier.EventType type = 6;</code>
       */
      public Builder setType(MessageProtos.EventCarrier.EventType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000020;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .EventCarrier.EventType type = 6;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000020);
        type_ = MessageProtos.EventCarrier.EventType.INSERT;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:EventCarrier)
    }

    static {
      defaultInstance = new EventCarrier(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:EventCarrier)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_EventCarrier_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_EventCarrier_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rWeWrite.proto\"\323\001\n\014EventCarrier\022\014\n\004text" +
      "\030\001 \001(\t\022\022\n\nstartIndex\030\002 \001(\005\022\020\n\010endIndex\030\003" +
      " \001(\005\022\021\n\tcursorLoc\030\004 \001(\005\022\020\n\010globalID\030\005 \001(" +
      "\003\022%\n\004type\030\006 \001(\0162\027.EventCarrier.EventType" +
      "\"C\n\tEventType\022\n\n\006INSERT\020\000\022\n\n\006DELETE\020\001\022\n\n" +
      "\006CURSOR\020\002\022\010\n\004UNDO\020\003\022\010\n\004REDO\020\004B\017B\rMessage" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_EventCarrier_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_EventCarrier_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_EventCarrier_descriptor,
              new java.lang.String[] { "Text", "StartIndex", "EndIndex", "CursorLoc", "GlobalID", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
